version: 0.2
phases:
  install:
    runtime-versions:
        golang: 1.13
  build:
    commands:
      - mkdir -p /go/src/github.com/printezisn/serverless-blog-back/
      - cp -r * /go/src/github.com/printezisn/serverless-blog-back/
      - cd /go/src/github.com/printezisn/serverless-blog-back/
      - aws cloudformation package --template-file ./template.yml --s3-bucket $CODE_URI_BUCKET --output-template-file deployment_template.yml
      - make
      - make copy_to_s3
artifacts:
  files:
    - /go/src/github.com/printezisn/serverless-blog-back/deployment_template.yml