AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Parameters:
  CodeUriBucket:
    Description: "Required. The S3 bucket where the lambda code resides."
    Type: "String"
Resources:
  postsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "posts"
  EdnaBlogUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UserPoolName: EdnaBlogUsers
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
  EdnaBlogUserPoolTokenClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref EdnaBlogUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH
  EdnaBlogServiceApi:
    DependsOn: EdnaBlogUserPool
    Type: AWS::Serverless::Api
    Properties:
      Name: EdnaBlogServiceApi
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt "EdnaBlogUserPool.Arn"
  EdnaBlogFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: serverless-blog-back
      Runtime: go1.x
      CodeUri:
        Bucket: !Ref CodeUriBucket
        Key: serverless-blog-back.zip
      Events:
        EdnaBlogApiGetAll:
          Type: Api
          Properties:
            Path: /posts
            RestApiId: !Ref EdnaBlogServiceApi
            Method: GET
        EdnaBlogApiOptions:
          Type: Api
          Properties:
            Path: /posts
            RestApiId: !Ref EdnaBlogServiceApi
            Method: OPTIONS
        EdnaBlogApiGet:
          Type: Api
          Properties:
            Path: /posts/{id+}
            RestApiId: !Ref EdnaBlogServiceApi
            Method: GET
        EdnaBlogApiDelete:
          Type: Api
          Properties:
            Path: /posts/{id+}
            RestApiId: !Ref EdnaBlogServiceApi
            Method: DELETE
            Auth:
              Authorizer: CognitoAuthorizer
        EdnaBlogApiPut:
          Type: Api
          Properties:
            Path: /posts
            RestApiId: !Ref EdnaBlogServiceApi
            Method: PUT
            Auth:
              Authorizer: CognitoAuthorizer
        EdnaBlogApiPost:
          Type: Api
          Properties:
            Path: /posts
            RestApiId: !Ref EdnaBlogServiceApi
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer
