AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  CodeUriBucket:
    Description: 'Required. The S3 bucket where the lambda code resides.'
    Type: 'String'
  CodeUriKey:
    Description: 'Required. The key in the S3 bucket where the lambda code resides.'
    Type: 'String'
Resources:
  postsDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "id"
          AttributeType: "S"
        - 
          AttributeName: "creationTimestamp"
          AttributeType: "N"
      KeySchema: 
        - 
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "posts"
      GlobalSecondaryIndexes: 
        - 
          IndexName: "creationTimestamp-id-index"
          KeySchema: 
            - 
              AttributeName: "creationTimestamp"
              KeyType: "HASH"
            - 
              AttributeName: "id"
              KeyType: "RANGE"
          Projection: 
            NonKeyAttributes: 
              - "title"
              - "slug"
              - "description"
              - "revision"
              - "updateTimestamp"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput: 
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
  EdnaBlogFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: serverless-blog-back
      Runtime: go1.x
      CodeUri:
        Bucket: !Ref CodeUriBucket
        Key: !Ref CodeUriKey
      Events:
        EdnaBlogApiGetAll:
          Type: Api
          Properties:
            Path: /posts
            Method: GET
        EdnaBlogApiGet:
          Type: Api
          Properties:
            Path: /posts/{id+}
            Method: GET
        EdnaBlogApiDelete:
          Type: Api
          Properties:
            Path: /posts/{id+}
            Method: DELETE
        EdnaBlogApiPut:
          Type: Api
          Properties:
            Path: /posts
            Method: PUT
        EdnaBlogApiPost:
          Type: Api
          Properties:
            Path: /posts
            Method: POST